### ISSUE TITLE
Join efforts with mruby-cli

### ISSUE THREAD

**Issue by sagmor** [qtkmz/mrb#2]
Hi @qtkmz,

I've been looking at this project and thought that maybe we could merge this project with my [mruby-cli](https://github.com/sagmor/mruby-cli)

There's already a lot of synergy between both projects:
- Same target use
- Same executable name
- Same dependency (thor)

So it should be pretty straightforward to work together.
Take a look at it and let me know what you think.

**Comment by qtkmz** [comment]
HI, @sagmor 

If you're me look at my idea, thank you.

I do not want to be mrb can not be managed. I developed that I thought it was necessary to myself. we are developing what was wanted to make myself.

**Comment by mibamur** [comment]
Hi @sagmor
I can add https://rubygems.org/gems/mgem features to mruby-cli

**Comment by mibamur** [comment]
oops @sagmor 
sorry I thought you here https://github.com/hone/mruby-cli but you there https://github.com/sagmor/mruby-cli

**Comment by sagmor** [comment]
@mibamur no problem from my part 😄

**Comment by qtkmz** [comment]
I close this issue. thanks 👍
